// Generated from ../../src/dotgen/idltype.y - manual changes will be lost

























Data type and constant definitions
----------------------------------

All data types manipulated by Genom are described with a subset of the OMG
IDL syntax. Those types map into traditional programming languages types
using the specific mappings described in the
link:../mappings/index{outfilesuffix}[GenoM IDL mappings] section.



=== Type specification

The following set of type specifiers to represent
typed values is available:

[[dotgen-rule-type-spec]]
____
(56) type-spec             ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-simple-type-spec[simple-type-spec] +
                              | link:grammar{outfilesuffix}#dotgen-rule-constructed-type-spec[constructed-type-spec]
____
[[dotgen-rule-simple-type-spec]]
____
(57) simple-type-spec      ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-base-type-spec[base-type-spec] +
                              | link:grammar{outfilesuffix}#dotgen-rule-template-type-spec[template-type-spec] +
                              | link:grammar{outfilesuffix}#dotgen-rule-named-type[named-type]
____
[[dotgen-rule-constructed-type-spec]]
____
(92) constructed-type-spec ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-constructed-type[constructed-type]
____

==== Subtopics

* link:idltype-base{outfilesuffix}[IDL base types]:
  integers, floating point values ...
* link:idltype-tmpl{outfilesuffix}[IDL template types]:
  sequences, strings ...
* link:idltype-constr{outfilesuffix}[IDL constructed types]:
  structs, unions, enums, ...





































=== Type declaration

Type defined with the following syntax can then be used in the component
interface definition and anywhere a type value is expected.

[[dotgen-rule-type-dcl]]
____
(58) type-dcl              ::= ::
   "typedef" link:grammar{outfilesuffix}#dotgen-rule-type-declarator[type-declarator] ";" +
                              | "native" link:grammar{outfilesuffix}#dotgen-rule-identifier[identifier] ";" +
                              | "exception" link:grammar{outfilesuffix}#dotgen-rule-exception-list[exception-list] ";" +
                              | link:grammar{outfilesuffix}#dotgen-rule-constructed-type[constructed-type] ";" +
                              | link:grammar{outfilesuffix}#dotgen-rule-forward-dcl[forward-dcl] ";"
____
[[dotgen-rule-constructed-type]]
____
(93) constructed-type      ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-struct-type[struct-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-union-type[union-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-enum-type[enum-type]
____
[[dotgen-rule-type-declarator]]
____
(59) type-declarator       ::= ::
   ( link:grammar{outfilesuffix}#dotgen-rule-type-spec[type-spec] +
                              | link:grammar{outfilesuffix}#dotgen-rule-type-declarator[type-declarator] "," ) link:grammar{outfilesuffix}#dotgen-rule-declarator[declarator]
____

==== Typedef

Types are most often given a unique name thanks to a `typedef` declaration;
a name is also associated with a data type via the `struct`, `union`,
`enum`, `native` and `exception` declarations.

==== Native types

It is possible to hide the actual definition of a data type from Genom (and
its IDL parser) when it will never be directly used in the interface of the
component, but can nevertheless be needed by codels. These types can be
declared using the `native` attribute.

For example: `native foo;`













































==== Exceptions

Exceptions are thrown by services in case of error. The `exception` keyword
declares an exception, which is an identifier with an optional associated
data type.

[[dotgen-rule-exception-list]]
____
(60) exception-list        ::= ::
   { link:grammar{outfilesuffix}#dotgen-rule-exception-dcl[exception-dcl] "," } link:grammar{outfilesuffix}#dotgen-rule-exception-dcl[exception-dcl]
____
[[dotgen-rule-exception-dcl]]
____
(61) exception-dcl         ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-exception-name[exception-name] link:grammar{outfilesuffix}#dotgen-rule-opt-member-list[opt-member-list]
____
[[dotgen-rule-opt-member-list]]
____
(62) opt-member-list       ::= ::
   [ "{" ( "}" +
                              | link:grammar{outfilesuffix}#dotgen-rule-member-list[member-list] "}" ) ]
____

A simple exception declaration would be :

----
exception INVALID_SPEED;
----

or with an associated type (to store the actual value for instance):

----
exception INVALID_SPEED {
  double speed;
};
----









































































=== Constant declaration

Constants define read-only values that are used by the component, like the
maximal speed allowed for a motor or the physical bounds of a process that
will be controlled. The syntax is again very similar to `C` or `C++`:

[[dotgen-rule-const-dcl]]
____
(68) const-dcl             ::= ::
   "const" link:grammar{outfilesuffix}#dotgen-rule-const-type[const-type] link:grammar{outfilesuffix}#dotgen-rule-identifier[identifier] "=" link:grammar{outfilesuffix}#dotgen-rule-const-expr[const-expr] ";"
____
[[dotgen-rule-const-type]]
____
(69) const-type            ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-integer-type[integer-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-char-type[char-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-boolean-type[boolean-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-floating-pt-type[floating-pt-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-octet-type[octet-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-string-type[string-type] +
                              | link:grammar{outfilesuffix}#dotgen-rule-named-type[named-type]
____

For example: `const double max_speed = 72.0;`


















// eof
