// Generated from port.y - manual changes will be lost

























Port declaration
----------------

Ports implement the data flow between components as a publish/subscribe
model. Ports have a name and a type. They can be either `out` ports (for
publishing data) or `in` ports (for subscribing to a sibling `out` port).

[[dotgen-rule-port]]
____
(22) port                  ::= ::
   "port" link:grammar{outfilesuffix}#dotgen-rule-opt-multiple[opt-multiple] link:grammar{outfilesuffix}#dotgen-rule-port-dir[port-dir] link:grammar{outfilesuffix}#dotgen-rule-type-spec[type-spec] link:grammar{outfilesuffix}#dotgen-rule-identifier[identifier] link:grammar{outfilesuffix}#dotgen-rule-opt-properties[opt-properties] ";"
____
[[dotgen-rule-opt-multiple]]
____
(24) opt-multiple          ::= ::
   [ "multiple" ]
____
[[dotgen-rule-port-dir]]
____
(23) port-dir              ::= ::
   "in" +
                              | "out"
____

Ports are by default `single` ports, i.e. they define one type of exported
data. The optional `multiple` qualifier can be used to define a 'dynamic
list' of ports of the given type, instead of a single slot. Suchs ports are
accessed as an array indexed by strings. In this case, ports are created or
destroyed dynamically be the codels. The
link:../mappings/index{outfilesuffix}[IDL mappings] section for ports
explains how this is done.
























// eof
