// Generated from ../../src/dotgen/main.y - manual changes will be lost




























































































































































Specification
-------------

A dotgen specification consists of one or more statements. Statements are
either `genom` statements or IDL statements. `cpp` directives (see
link:preprocessing{outfilesuffix}[Preprocessing]) are handled at the lexical
level and do not interfere with the specification grammar.

[[dotgen-rule-specification]]
____
(1) specification         ::= ::
   { link:grammar{outfilesuffix}#dotgen-rule-statement[statement] }
____
[[dotgen-rule-statement]]
____
(2) statement             ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-component[component] +
                              | link:grammar{outfilesuffix}#dotgen-rule-interface[interface] +
                              | link:grammar{outfilesuffix}#dotgen-rule-idl-statement[idl-statement]
____

[[dotgen-rule-idl-statement]]
____
(4) idl-statement         ::= ::
   link:grammar{outfilesuffix}#dotgen-rule-module[module] +
                              | link:grammar{outfilesuffix}#dotgen-rule-const-dcl[const-dcl] +
                              | link:grammar{outfilesuffix}#dotgen-rule-type-dcl[type-dcl]
____

Definitions are named by the mean of
link:indentifier{outfilesuffix}[identifiers].

A `genom` statement defines link:component{outfilesuffix}[components] or
link:interface{outfilesuffix}[interfaces].

An IDL statement defines link:typedef{outfilesuffix}[types],
link:typedef{outfilesuffix}[constants] or link:module{outfilesuffix}[IDL
modules] containing types and constants.  The syntax follows closely the
subset the 'OMG' IDL specification corresponding to type and constants
definitions (see Chapter 7 of the CORBA specification, Object Management
Group, version 3.1. Part I: CORBA interfaces).  Note that this subset of the
dogten grammar is not in any manner tied to OMG IDL and may diverge from
future OMG specifications.
























































































































// eof
