.\"
.\" Copyright (c) 2010 LAAS/CNRS
.\" All rights reserved.
.\"
.\" Permission to use, copy, modify, and  distribute this  software for any
.\" purpose with or  without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE  SOFTWARE  IS   PROVIDED  "AS IS"  AND  THE  AUTHOR  DISCLAIMS  ALL
.\" WARRANTIES  WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING   ALL  IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR
.\" BE LIABLE FOR ANY  SPECIAL, DIRECT, INDIRECT, OR  CONSEQUENTIAL DAMAGES
.\" OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA  OR PROFITS,
.\" WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
.\" ARISING OUT  OF OR IN CONNECTION  WITH THE  USE OR PERFORMANCE  OF THIS
.\" SOFTWARE.
.\"
.\"                                       Anthony Mallet on Sun Jun  6 2010
.Dd @date@
.Os GenoM @version@
.Dt GENOM \&1 "GenoM Manual Pages"
.Sh NAME
.Nm genom3
.Nd software component generator
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Ar general options
.Ar template
.Op Ar template options
.Ar file
.Ek
@genom-options@
.Sh FILES
.Bl -tag -width pancake
.It Pa @CPP@
Default C preprocessor
.It Pa @docdir@
Complete PDF, HTML and text documentations.
.It Pa @prefix@/share/genom/@version@/templates
Default template directory.
.Sh SEE ALSO
.Xr cpp 1
.Sh HISTORY
Genom development was initiated by
.An -nosplit
.An "Sara Fleury"
and
.An "Matthieu Herrb"
in 1994.
The first opensource version, labelled version 2.x, was released in 2004.
The reflexion and development of version 3 was started by
.An "Anthony Mallet"
in 2009, with the great help of
.An "C\['e]dric Pasteur"
who quickly developed the first prototype in the context of his master training
period.
.Sh AUTHORS
.An -nosplit
.An "Sara Fleury",
.An "Matthieu Herrb",
.An "Anthony Mallet",
.An "C\['e]dric Pasteur"
and people working on the
.An "LAAS openrobots projet"
.Aq openrobots@laas.fr .
.Sh BUGS
Bug and problem reports are always apreciated. Please send an e-mail with
detailed information about the problem and the context in which it appeared to
.Aq openrobots@laas.fr .
