//
// Copyright (c) 2014-2015,2017 LAAS/CNRS
// All rights reserved.
//
// Redistribution and use  in source  and binary  forms,  with or without
// modification, are permitted provided that the following conditions are
// met:
//
//   1. Redistributions of  source  code must retain the  above copyright
//      notice and this list of conditions.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice and  this list of  conditions in the  documentation and/or
//      other materials provided with the distribution.
//
//                                      Anthony Mallet on Wed Jul 16 2014
//

ifdef::sidebartoc[]
include::_Sidebar.adoc[]
endif::[]

Genom component model
---------------------

.Overview
[graphviz, genom-component-model, svg, opts="inline"]
--
digraph {
rankdir = BT

node [
  fontname = "sans"
  fontsize = 10
  shape = "none"
  margin = 0
  width = 0
  height = 0
]

component [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Component</td></tr>
    <tr><td align="left" balign="left">name<br/>provides<br/>uses</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

ids [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>IDS</td></tr>
    <tr><td align="left">members</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

exception [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Exception</td></tr>
    <tr><td align="left">detail</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

task [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Task</td></tr>
    <tr><td align="left" balign="left">name<br/>period</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

service [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Attribute</td></tr>
    <tr><td align="left" balign="left">
name<br/>type<br/>inputs<br/>outputs<br/>local variables</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

attribute [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Attribute</td></tr>
    <tr><td align="left">name</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

function [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Function</td></tr>
    <tr><td align="left">name</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

activity [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Activity</td></tr>
    <tr><td align="left">name</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

port [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Port</td></tr>
    <tr><td align="left">name<br align="left"/>direction</td></tr>
    <tr><td><br/></td></tr>
  </table>>
]

fsm [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>State Machine</td></tr>
    <tr><td><br/></td></tr>
    <tr><td align="left">start()<br/>stop()</td></tr>
  </table>>
]

codel [
  label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="4">
    <tr><td>Codel</td></tr>
    <tr><td><br/></td></tr>
    <tr><td align="left">run()</td></tr>
  </table>>
]

{
  rank=same
  attribute
  function
  activity
}

{
  rank=same
  port
  service
  task
  ids
  exception
}

{
  rank=same
  fsm
  codel
}

edge [
  fontname = "sans"
  fontsize = 8
  arrowhead = "diamond"
  arrowtail = "none"
  labeldistance=1.5
  labelangle=-30
]

service -> component [taillabel="1", headlabel="0..*"]
port -> component [taillabel="1", headlabel="0..*"]
ids -> component [taillabel="1", headlabel="0..1"]
task -> component [taillabel="1", headlabel="0..*"]

fsm -> activity [taillabel="1", headlabel="1"]
codel -> attribute [taillabel="1", headlabel="1"]
codel -> function [taillabel="1", headlabel="1..*"]
codel -> fsm [taillabel="1", headlabel="1..*"]

edge [
  arrowhead = "none"
]

activity -> task [taillabel="1", headlabel="0..*"]
service -> exception [taillabel="0..*", headlabel="1..*"]

codel -> port [label="updates"]
codel -> ids [label="updates"]

edge [
  arrowhead = "empty"
]

attribute -> service
function -> service
activity -> service
}
--
