<?
# print all types except ids in idl format
for t in comp.typesVect():
    if t.identifier() != IDSType.identifier():
	print MapTypeToIdl(t) + ";"
?>

interface I<!capCompName!>
{
<?
for s in servicesMap:
  print "   " + service_idl_signature(s.data())
?>};
