<?
currentTask = comp.task(currentTaskName)
# print all types except ids in idl format
for t in comp.typesVect():
    if t.identifier() != IDSType.identifier():
	print MapTypeToIdl(t) + ";"
?> 

interface I<!capCompName!><!currentTaskName!> 
{
<?
for s in servicesMap:
    service = s.data()
    if service.type != ServiceType.Control and service.taskName == currentTaskName:
	print service_idl_signature(service)
?>};
