:revision: 2.99.39
:year: 2020

ifdef::sidebartoc[]
include::_Sidebar.adoc[]
endif::[]


Copying
-------

Each file in the source distribution has a copyright/licensing statement at the
beginning of the file. The following is intended to summarize the copyright
status of the individual files.

* Except as listed below, all source files and documentation are subject to
  this copyright notice:

____
Copyright (c) 2009-{year} LAAS/CNRS
All rights reserved.

Redistribution  and  use  in  source  and binary  forms,  with  or  without
modification, are permitted provided that the following conditions are met:

1. Redistributions of  source  code must retain the  above copyright
   notice and this list of conditions.
2. Redistributions in binary form must reproduce the above copyright
   notice and  this list of  conditions in the  documentation and/or
   other materials provided with the distribution.

THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
____


* Files under the `pcpp/` directory are subject to the following copyright
  notices:

____
Copyright (c) 2004,2010 Anders Magnusson (<ragge@ludd.luth.se>).
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
____

____
Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code and documentation must retain the above
copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
All advertising materials mentioning features or use of this software
must display the following acknowledgement:

  This product includes software developed or owned by Caldera
  International, Inc.

Neither the name of Caldera International, Inc. nor the names of other
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

USE OF THE SOFTWARE PROVIDED FOR UNDER THIS LICENSE BY CALDERA
INTERNATIONAL, INC. AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL CALDERA INTERNATIONAL, INC. BE LIABLE
FOR ANY DIRECT, INDIRECT INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OFLIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
____


* md5 digest and the longest common subsequence of two files are part of tcllib
  http://tcllib.sourceforge.net/.

 * `md5.tcl` is copyright (C) 2003
    Pat Thoyts <patthoyts@users.sourceforge.net>.
 * `lcs.tcl` is copyright (C) 2003 by Kevin B. Kenny. All rights reserved.

+
Both are subject to the following copyright notice:

____
The authors hereby  grant permission to use, copy,  modify, distribute, and
license this software and its  documentation for any purpose, provided that
existing copyright notices are retained  in all copies and that this notice
is included  verbatim in any distributions. No  written agreement, license,
or royalty fee  is required for any of  the authorized uses.  Modifications
to this  software may be copyrighted  by their authors and  need not follow
the licensing terms described here, provided that the new terms are clearly
indicated on the first page of each file where they apply.

IN NO  EVENT SHALL THE AUTHORS OR  DISTRIBUTORS BE LIABLE TO  ANY PARTY FOR
DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF,
EVEN IF THE AUTHORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THE  AUTHORS   AND  DISTRIBUTORS  SPECIFICALLY   DISCLAIM  ANY  WARRANTIES,
INCLUDING, BUT  NOT LIMITED TO, THE IMPLIED  WARRANTIES OF MERCHANTABILITY,
FITNESS FOR  A PARTICULAR PURPOSE,  AND NON-INFRINGEMENT. THIS  SOFTWARE IS
PROVIDED ON  AN "AS  IS" BASIS,  AND THE AUTHORS  AND DISTRIBUTORS  HAVE NO
OBLIGATION  TO  PROVIDE  MAINTENANCE,  SUPPORT, UPDATES,  ENHANCEMENTS,  OR
MODIFICATIONS.

GOVERNMENT  USE:  If you  are  acquiring this  software  on  behalf of  the
U.S. government, the Government shall  have only "Restricted Rights" in the
software and  related documentation as  defined in the  Federal Acquisition
Regulations (FARs)  in Clause 52.227.19 (c)  (2). If you  are acquiring the
software  on behalf of  the Department  of Defense,  the software  shall be
classified as "Commercial Computer  Software" and the Government shall have
only  "Restricted Rights"  as defined  in  Clause 252.227-7013  (c) (1)  of
DFARs. Notwithstanding the foregoing, the authors grant the U.S. Government
and  others acting  in  its behalf  permission  to use  and distribute  the
software in accordance with the terms specified in this license.
____


* `compat/getline.c` is subject to the following copyright notice:

____
Copyright (c) 2009 The NetBSD Foundation, Inc.

This code is derived from software contributed to The NetBSD Foundation
by Roy Marples. It has been further adapted to use fgets() instead of
internal stdio FILE structure details to provide a generic replacement
function when a system getline() is missing.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
____


* `compat/strlcat.c` and `compat/strlcpy.c` are subject to the following
  copyright notice:

____
Copyright (c) 1998 Todd C. Miller <Todd.Miller@courtesan.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND TODD C. MILLER DISCLAIMS ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL TODD C. MILLER BE LIABLE
FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
____
